import { StyleSheet, Dimensions, Platform } from "react-native";

const { width } = Dimensions.get("window");

/* Light design tokens */
const COLOR = {
  bg: "#f7f9fc",           // nền app sáng dịu
  surface: "#ffffff",      // nền thẻ
  line: "#e8edf3",         // viền nhạt
  text: "#0f172a",         // chữ chính (slate-900)
  textDim: "#667085",      // chữ phụ
  primary: "#2563eb",      // xanh chủ đạo
  primarySoft: "#eff6ff",  // xanh rất nhạt
  success: "#10b981",
  warning: "#f59e0b",
  danger: "#ef4444",
};

const RADIUS = { sm: 8, md: 12, lg: 16, xl: 20, full: 999 };
const SPACE = { xs: 6, sm: 10, md: 14, lg: 18, xl: 22, xxl: 28 };

const SHADOW = Platform.select({
  ios: {
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  android: { elevation: 3 },
});

export const styles = StyleSheet.create({
  /* Base styles */
  container: { flex: 1, backgroundColor: COLOR.bg },

  /* Header */
  screenHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACE.lg,
    paddingVertical: SPACE.md,
    backgroundColor: COLOR.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLOR.line,
  },
  screenTitle: { fontSize: 18, fontWeight: "700", color: COLOR.text, letterSpacing: 0.2 },
  backButton: { fontSize: 16, color: COLOR.primary, fontWeight: "600" },
  editButton: { fontSize: 16, color: COLOR.primary, fontWeight: "700" },
  saveButton: { fontSize: 16, color: COLOR.success, fontWeight: "700" },
  resetButton: { fontSize: 14, color: COLOR.danger, fontWeight: "600" },
  headerRight: { alignItems: "flex-end" },
  reviewCount: { fontSize: 12, color: COLOR.textDim },

  /* Tutor Info */
  tutorInfoContent: { flex: 1, marginBottom: 80 },
  tutorInfoAvatar: {
    backgroundColor: COLOR.surface,
    alignItems: "center",
    paddingVertical: SPACE.xxl,
    borderBottomWidth: 1,
    borderBottomColor: COLOR.line,
  },
  avatarIcon: { fontSize: 82, marginBottom: SPACE.sm },
  tutorInfoName: { fontSize: 24, fontWeight: "800", color: COLOR.text, marginBottom: 6 },
  tutorInfoSpecialty: { fontSize: 15, color: COLOR.primary, fontWeight: "700", marginBottom: SPACE.sm },
  tutorInfoRating: { flexDirection: "row", alignItems: "center", gap: 8 },
  ratingStars: { fontSize: 16, color: COLOR.warning },
  ratingText: { fontSize: 13, color: COLOR.textDim },

  infoSection: {
    backgroundColor: COLOR.surface,
    marginTop: SPACE.sm,
    marginHorizontal: 15,
    paddingHorizontal: SPACE.lg,
    paddingVertical: SPACE.lg,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
    ...SHADOW,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: COLOR.text,
    marginBottom: SPACE.md,
    paddingBottom: SPACE.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLOR.line,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: SPACE.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f4f7",
  },
  infoLabel: { fontSize: 14, color: COLOR.textDim, fontWeight: "600", flex: 1 },
  infoValue: { fontSize: 14, color: COLOR.text, flex: 2, textAlign: "right" },
  infoInput: {
    fontSize: 14,
    color: COLOR.text,
    flex: 2,
    textAlign: "right",
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACE.sm,
    paddingVertical: 8,
    backgroundColor: "#fafafa",
  },
  infoTextArea: { height: 72, textAlignVertical: "top", textAlign: "left" },

  workingAreasContainer: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  areaTag: {
    backgroundColor: COLOR.primarySoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: "#c7d2fe",
  },
  areaTagText: { fontSize: 12, color: COLOR.primary, fontWeight: "700" },

  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  statCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: COLOR.surface,
    padding: SPACE.md,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  statNumber: { fontSize: 20, fontWeight: "900", color: COLOR.primary, marginBottom: 4 },
  statLabel: { fontSize: 12, color: COLOR.textDim, textAlign: "center" },

  editActions: { flexDirection: "row", gap: SPACE.md, paddingHorizontal: SPACE.lg, paddingVertical: SPACE.lg },
  cancelEditButton: {
    flex: 1,
    backgroundColor: "#f3f4f6",
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  cancelEditButtonText: { fontSize: 16, color: COLOR.textDim, fontWeight: "600" },
  saveEditButton: {
    flex: 1,
    backgroundColor: COLOR.primary,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  saveEditButtonText: { fontSize: 16, color: "#ffffff", fontWeight: "800" },

  /* Tutor Area */
  areaContent: { flex: 1, marginBottom: 80 },
  areaStatsSection: {
    backgroundColor: COLOR.surface,
    margin: SPACE.lg,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
    ...SHADOW,
  },
  areaStatsGrid: { flexDirection: "row", gap: SPACE.md },
  areaStatCard: {
    flex: 1,
    backgroundColor: "#f9fafb",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  areaStatNumber: { fontSize: 18, fontWeight: "900", color: COLOR.primary, marginBottom: 4 },
  areaStatLabel: { fontSize: 12, color: COLOR.textDim, textAlign: "center" },

  areaSection: {
    backgroundColor: COLOR.surface,
    marginHorizontal: SPACE.lg,
    marginBottom: SPACE.md,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  sectionSubtitle: { fontSize: 14, color: COLOR.textDim, marginBottom: SPACE.md, lineHeight: 20 },

  radiusSelector: { gap: SPACE.md },
  radiusLabel: { fontSize: 16, fontWeight: "800", color: COLOR.text },
  radiusButtons: { flexDirection: "row", gap: 10 },
  radiusButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    alignItems: "center",
    backgroundColor: "#f9fafb",
  },
  selectedRadiusButton: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  radiusButtonText: { fontSize: 14, color: COLOR.textDim, fontWeight: "600" },
  selectedRadiusButtonText: { color: COLOR.primary, fontWeight: "800" },

  areasGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  areaCard: {
    width: "48%",
    backgroundColor: COLOR.surface,
    padding: SPACE.md,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  selectedAreaCard: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  disabledAreaCard: { opacity: 0.55 },

  areaCardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  areaCardName: { fontSize: 16, fontWeight: "800", color: COLOR.text },
  selectedAreaCardName: { color: COLOR.primary },
  areaCardCheck: { fontSize: 16, color: COLOR.primary, fontWeight: "900" },
  areaCardDistrict: { fontSize: 12, color: COLOR.textDim, marginBottom: 4 },
  selectedAreaCardDistrict: { color: "#1d4ed8" },
  areaCardDistance: { fontSize: 12, color: "#94a3b8" },
  selectedAreaCardDistance: { color: "#1d4ed8" },
  areaCardDisabled: { fontSize: 11, color: COLOR.danger, fontWeight: "700", marginTop: 6 },

  quickAreaActions: { flexDirection: "row", gap: SPACE.md },
  quickAreaButton: {
    flex: 1,
    backgroundColor: "#f9fafb",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  quickAreaButtonIcon: { fontSize: 22, marginBottom: 8, color: COLOR.text },
  quickAreaButtonText: { fontSize: 14, fontWeight: "800", color: COLOR.text, marginBottom: 4 },
  quickAreaButtonSubtext: { fontSize: 12, color: COLOR.textDim },

  areaTips: {
    backgroundColor: "#fff7ed",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "#fed7aa",
  },
  areaTipsTitle: { fontSize: 16, fontWeight: "800", color: "#b45309", marginBottom: 6 },
  areaTipsText: { fontSize: 14, color: "#b45309", lineHeight: 20, opacity: 0.9 },

  /* Reviews */
  reviewsContent: { flex: 1, marginBottom: 80 },
  overallRatingSection: {
    backgroundColor: COLOR.surface,
    margin: SPACE.lg,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
    ...SHADOW,
  },
  overallRatingCard: { flexDirection: "row", gap: 20 },
  overallRatingLeft: { alignItems: "center", flex: 1 },
  overallRatingNumber: { fontSize: 48, fontWeight: "900", color: COLOR.warning, marginBottom: 6, letterSpacing: 0.3 },
  overallRatingStars: { fontSize: 20, marginBottom: 6, color: COLOR.warning },
  overallRatingText: { fontSize: 14, color: COLOR.textDim },
  overallRatingRight: { flex: 2, gap: 6 },

  ratingDistributionRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  ratingDistributionStars: { fontSize: 12, width: 34, color: COLOR.text },
  ratingDistributionBar: {
    flex: 1,
    height: 10,
    backgroundColor: "#eef2f7",
    borderRadius: 6,
    overflow: "hidden",
  },
  ratingDistributionFill: { height: "100%", backgroundColor: COLOR.warning },
  ratingDistributionCount: { fontSize: 12, color: COLOR.textDim, width: 22, textAlign: "right" },

  reviewFilterTabs: {
    flexDirection: "row",
    backgroundColor: "transparent",
    paddingHorizontal: SPACE.lg,
    paddingVertical: SPACE.md,
    gap: 10,
  },
  reviewFilterTab: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: RADIUS.full,
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  activeReviewFilterTab: { backgroundColor: COLOR.primarySoft, borderColor: COLOR.primary },
  reviewFilterTabText: { fontSize: 12, color: COLOR.textDim, fontWeight: "700" },
  activeReviewFilterTabText: { color: COLOR.primary, fontWeight: "900" },

  reviewsList: { paddingHorizontal: SPACE.lg, paddingVertical: SPACE.md, gap: SPACE.md },
  reviewCard: {
    backgroundColor: COLOR.surface,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
    ...SHADOW,
  },
  reviewHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 },
  reviewCustomerInfo: { flexDirection: "row", alignItems: "center", flex: 1 },
  reviewCustomerAvatar: { fontSize: 32, marginRight: 12 },
  reviewCustomerDetails: { flex: 1 },
  reviewCustomerName: { fontSize: 16, fontWeight: "800", color: COLOR.text, marginBottom: 2 },
  reviewDate: { fontSize: 12, color: COLOR.textDim },
  reviewMenuButton: { padding: 6 },
  reviewMenuIcon: { fontSize: 18, color: COLOR.textDim },

  reviewRating: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  reviewStars: { fontSize: 16, color: COLOR.warning },
  reviewService: { fontSize: 14, color: COLOR.textDim, marginLeft: 8 },

  reviewComment: { fontSize: 14, color: COLOR.text, lineHeight: 20, marginBottom: 12 },

  reviewImages: { flexDirection: "row", gap: 8, marginBottom: 12 },
  reviewImagePlaceholder: {
    width: 64,
    height: 64,
    backgroundColor: "#f3f4f6",
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  reviewImageIcon: { fontSize: 24, color: COLOR.textDim },

  reviewFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  reviewMeta: { flex: 1 },
  reviewOrderId: { fontSize: 12, color: COLOR.textDim, marginBottom: 2 },
  reviewHelpful: { fontSize: 12, color: COLOR.textDim },

  replyButton: {
    backgroundColor: COLOR.primarySoft,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLOR.primary,
  },
  replyButtonText: { fontSize: 12, color: COLOR.primary, fontWeight: "800" },

  reviewTipsSection: { paddingHorizontal: SPACE.lg, paddingVertical: SPACE.md },
  reviewTips: {
    backgroundColor: "#eff6ff",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "#c7d2fe",
  },
  reviewTipsTitle: { fontSize: 16, fontWeight: "800", color: "#1d4ed8", marginBottom: 6 },
  reviewTipsText: { fontSize: 14, color: "#334155", lineHeight: 20 },

  /* Support */
  supportTabContainer: {
    flexDirection: "row",
    backgroundColor: COLOR.surface,
    paddingHorizontal: SPACE.lg,
    paddingTop: SPACE.md,
    borderBottomWidth: 1,
    borderBottomColor: COLOR.line,
  },
  supportTab: { flex: 1, paddingVertical: SPACE.md, alignItems: "center", borderBottomWidth: 2, borderBottomColor: "transparent" },
  activeSupportTab: { borderBottomColor: COLOR.primary },
  supportTabText: { fontSize: 14, color: COLOR.textDim, fontWeight: "700" },
  activeSupportTabText: { color: COLOR.primary, fontWeight: "900" },

  supportContent: { flex: 1, marginBottom: 80 },
  quickSupportSection: {
    backgroundColor: COLOR.surface,
    margin: SPACE.lg,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  quickSupportButtons: { flexDirection: "row", gap: SPACE.md },
  quickSupportButton: {
    flex: 1,
    backgroundColor: "#f9fafb",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  quickSupportIcon: { fontSize: 24, marginBottom: 8, color: COLOR.text },
  quickSupportText: { fontSize: 14, fontWeight: "800", color: COLOR.text, marginBottom: 2 },
  quickSupportSubtext: { fontSize: 12, color: COLOR.textDim },

  faqSection: {
    backgroundColor: COLOR.surface,
    marginHorizontal: SPACE.lg,
    marginBottom: SPACE.lg,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  faqContainer: { gap: SPACE.sm },
  faqItem: {
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    overflow: "hidden",
    backgroundColor: "#f9fafb",
  },
  faqQuestion: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: SPACE.md,
  },
  faqQuestionText: { fontSize: 14, fontWeight: "800", color: COLOR.text, flex: 1 },
  faqArrow: { fontSize: 18, color: COLOR.textDim, fontWeight: "900" },
  faqAnswer: {
    padding: SPACE.md,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: COLOR.line,
  },
  faqAnswerText: { fontSize: 14, color: COLOR.text, lineHeight: 20 },

  supportCategoriesSection: {
    backgroundColor: COLOR.surface,
    margin: SPACE.lg,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  supportCategoriesGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  supportCategoryCard: {
    width: "48%",
    backgroundColor: "#f9fafb",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  selectedSupportCategory: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  supportCategoryIcon: { fontSize: 32, marginBottom: 8, color: COLOR.text },
  supportCategoryTitle: { fontSize: 14, fontWeight: "800", color: COLOR.text, marginBottom: 4, textAlign: "center" },
  supportCategoryDescription: { fontSize: 12, color: COLOR.textDim, textAlign: "center", lineHeight: 16 },

  contactFormSection: {
    backgroundColor: COLOR.surface,
    marginHorizontal: SPACE.lg,
    marginBottom: SPACE.lg,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  contactForm: { gap: SPACE.lg },
  formGroup: { gap: 8 },
  formLabel: { fontSize: 14, fontWeight: "800", color: COLOR.text },
  contactInput: {
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACE.md,
    paddingVertical: 12,
    fontSize: 14,
    color: COLOR.text,
    backgroundColor: "#ffffff",
  },
  contactTextArea: { height: 110, textAlignVertical: "top" },

  prioritySelector: { flexDirection: "row", gap: 10 },
  priorityButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderRadius: RADIUS.md,
    alignItems: "center",
    backgroundColor: "#f9fafb",
    borderColor: COLOR.line,
  },
  selectedPriorityButton: { backgroundColor: "#fff7ed", borderColor: "#fed7aa" },
  priorityButtonText: { fontSize: 12, fontWeight: "800", color: COLOR.text },

  submitContactButton: {
    backgroundColor: COLOR.primary,
    paddingVertical: 12,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  submitContactButtonText: { fontSize: 16, color: "#ffffff", fontWeight: "900" },

  supportTipsSection: { paddingHorizontal: SPACE.lg, paddingBottom: SPACE.lg },
  supportTips: {
    backgroundColor: "#eff6ff",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "#c7d2fe",
  },
  supportTipsTitle: { fontSize: 16, fontWeight: "900", color: "#1d4ed8", marginBottom: 6 },
  supportTipsText: { fontSize: 14, color: "#334155", lineHeight: 20 },

  /* Settings */
  settingsContent: { flex: 1, marginBottom: 80 },
  settingsSection: {
    backgroundColor: COLOR.surface,
    marginTop: SPACE.sm,
    paddingVertical: SPACE.lg,
    borderTopWidth: 1,
    borderTopColor: COLOR.line,
    borderBottomWidth: 1,
    borderBottomColor: COLOR.line,
  },
  settingsSectionTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: COLOR.text,
    paddingHorizontal: SPACE.lg,
    marginBottom: SPACE.md,
  },
  settingsGroup: { paddingHorizontal: SPACE.lg },
  settingItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: SPACE.md,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f4f7",
  },
  settingInfo: { flex: 1 },
  settingTitle: { fontSize: 16, color: COLOR.text, fontWeight: "800", marginBottom: 2 },
  settingSubtitle: { fontSize: 12, color: COLOR.textDim, lineHeight: 16 },
  settingValue: { fontSize: 14, color: COLOR.primary, fontWeight: "800" },

  workingModeSelector: { paddingHorizontal: SPACE.lg, gap: 10 },
  workingModeOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: SPACE.md,
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    backgroundColor: "#f9fafb",
  },
  selectedWorkingMode: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  workingModeInfo: { flex: 1 },
  workingModeLabel: { fontSize: 14, fontWeight: "900", color: COLOR.text, marginBottom: 2 },
  selectedWorkingModeLabel: { color: COLOR.primary },
  workingModeDesc: { fontSize: 12, color: COLOR.textDim },
  workingModeCheck: { fontSize: 16, color: COLOR.primary, fontWeight: "900" },

  orderLimitSelector: { flexDirection: "row", paddingHorizontal: SPACE.lg, gap: 8 },
  orderLimitButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    alignItems: "center",
    backgroundColor: "#f9fafb",
  },
  selectedOrderLimit: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  orderLimitText: { fontSize: 14, color: COLOR.textDim, fontWeight: "800" },
  selectedOrderLimitText: { color: COLOR.primary },

  settingActionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: SPACE.md + 2,
    paddingHorizontal: SPACE.lg,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f4f7",
  },
  settingActionText: { fontSize: 16, color: COLOR.text, fontWeight: "800" },
  dangerText: { color: COLOR.danger },
  settingActionArrow: { fontSize: 18, color: COLOR.textDim },

  appInfoContainer: { paddingHorizontal: SPACE.lg },
  appInfoItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: SPACE.md,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f4f7",
  },
  appInfoLabel: { fontSize: 14, color: COLOR.textDim },
  appInfoValue: { fontSize: 14, color: COLOR.text, fontWeight: "800" },
  appInfoAction: { fontSize: 14, color: COLOR.primary, fontWeight: "800" },

  /* Personal Info */
  personalInfoContent: { flex: 1, marginBottom: 80 },
  personalInfoAvatar: {
    backgroundColor: COLOR.surface,
    alignItems: "center",
    paddingVertical: SPACE.xxl,
    borderBottomWidth: 1,
    borderBottomColor: COLOR.line,
  },
  personalInfoName: { fontSize: 24, fontWeight: "900", color: COLOR.text, marginBottom: SPACE.sm },
  membershipBadge: { backgroundColor: "#fde68a", paddingHorizontal: 12, paddingVertical: 4, borderRadius: RADIUS.full, marginBottom: 8 },
  membershipText: { fontSize: 12, color: "#1f2937", fontWeight: "900" },
  memberSinceText: { fontSize: 14, color: COLOR.textDim },

  personalInfoSection: {
    backgroundColor: COLOR.surface,
    marginTop: SPACE.sm,
    paddingHorizontal: SPACE.lg,
    paddingVertical: SPACE.lg,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  personalInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: SPACE.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f4f7",
  },
  personalInfoLabel: { fontSize: 14, color: COLOR.textDim, fontWeight: "800", flex: 1 },
  personalInfoValue: { fontSize: 14, color: COLOR.text, flex: 2, textAlign: "right" },
  personalInfoInput: {
    fontSize: 14,
    color: COLOR.text,
    flex: 2,
    textAlign: "right",
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACE.sm,
    paddingVertical: 8,
    backgroundColor: "#fafafa",
  },
  personalInfoTextArea: { height: 72, textAlignVertical: "top", textAlign: "left" },

  genderSelector: { flexDirection: "row", flex: 2, justifyContent: "flex-end", gap: 8 },
  genderOption: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.full,
    backgroundColor: "#f9fafb",
  },
  selectedGenderOption: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  genderOptionText: { fontSize: 12, color: COLOR.textDim, fontWeight: "800" },
  selectedGenderOptionText: { color: COLOR.primary },

  accountStatsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  accountStatCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: COLOR.surface,
    padding: SPACE.md,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  accountStatNumber: { fontSize: 20, fontWeight: "900", color: COLOR.primary, marginBottom: 4 },
  accountStatLabel: { fontSize: 12, color: COLOR.textDim, textAlign: "center" },

  servicePreferences: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  preferenceTag: {
    backgroundColor: "#ecfdf5",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  preferenceTagText: { fontSize: 12, color: COLOR.success, fontWeight: "900" },

  /* Customer Settings */
  timePreferenceSelector: { paddingHorizontal: SPACE.lg, gap: 10 },
  timePreferenceOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: SPACE.md,
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    backgroundColor: "#f9fafb",
  },
  selectedTimePreference: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  timePreferenceInfo: { flex: 1 },
  timePreferenceLabel: { fontSize: 14, fontWeight: "900", color: COLOR.text, marginBottom: 2 },
  selectedTimePreferenceLabel: { color: COLOR.primary },
  timePreferenceTime: { fontSize: 12, color: COLOR.textDim },
  timePreferenceCheck: { fontSize: 16, color: COLOR.primary, fontWeight: "900" },

  distanceSelector: { flexDirection: "row", paddingHorizontal: SPACE.lg, gap: 8 },
  distanceButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    alignItems: "center",
    backgroundColor: "#f9fafb",
  },
  selectedDistance: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  distanceText: { fontSize: 14, color: COLOR.textDim, fontWeight: "800" },
  selectedDistanceText: { color: COLOR.primary },

  priceRangeSelector: { paddingHorizontal: SPACE.lg, gap: 10 },
  priceRangeOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: SPACE.md,
    borderWidth: 1,
    borderColor: COLOR.line,
    borderRadius: RADIUS.md,
    backgroundColor: "#f9fafb",
  },
  selectedPriceRange: { borderColor: COLOR.primary, backgroundColor: COLOR.primarySoft },
  priceRangeInfo: { flex: 1 },
  priceRangeLabel: { fontSize: 14, fontWeight: "900", color: COLOR.text, marginBottom: 2 },
  selectedPriceRangeLabel: { color: COLOR.primary },
  priceRangeRange: { fontSize: 12, color: COLOR.textDim },
  priceRangeCheck: { fontSize: 16, color: COLOR.primary, fontWeight: "900" },

  /* About Us */
  aboutTabContainer: {
    flexDirection: "row",
    backgroundColor: COLOR.surface,
    paddingHorizontal: SPACE.lg,
    paddingTop: SPACE.md,
    borderBottomWidth: 1,
    borderBottomColor: COLOR.line,
  },
  aboutTab: { flex: 1, paddingVertical: SPACE.md, alignItems: "center", borderBottomWidth: 2, borderBottomColor: "transparent" },
  activeAboutTab: { borderBottomColor: COLOR.primary },
  aboutTabText: { fontSize: 14, color: COLOR.textDim, fontWeight: "800" },
  activeAboutTabText: { color: COLOR.primary },

  aboutContent: { flex: 1, marginBottom: 80 },
  aboutSection: {
    backgroundColor: COLOR.surface,
    marginHorizontal: SPACE.lg,
    marginVertical: SPACE.sm,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  companyLogo: { alignItems: "center", paddingVertical: SPACE.lg },
  logoIcon: { fontSize: 60, marginBottom: SPACE.sm, color: COLOR.text },
  companyName: { fontSize: 28, fontWeight: "900", color: COLOR.text, marginBottom: 6 },
  companySlogan: { fontSize: 16, color: COLOR.textDim, textAlign: "center", fontStyle: "italic" },

  missionVisionContainer: { gap: SPACE.md },
  missionCard: {
    backgroundColor: "#eff6ff",
    padding: SPACE.lg,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  missionIcon: { fontSize: 32, marginBottom: SPACE.sm, color: COLOR.text },
  missionTitle: { fontSize: 18, fontWeight: "900", color: "#1d4ed8", marginBottom: 6 },
  missionText: { fontSize: 14, color: "#334155", lineHeight: 20 },

  visionCard: {
    backgroundColor: "#ecfdf5",
    padding: SPACE.lg,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  visionIcon: { fontSize: 32, marginBottom: SPACE.sm, color: COLOR.text },
  visionTitle: { fontSize: 18, fontWeight: "900", color: "#047857", marginBottom: 6 },
  visionText: { fontSize: 14, color: "#14532d", lineHeight: 20 },

  coreValuesContainer: { flexDirection: "row", flexWrap: "wrap", gap: SPACE.md },
  valueItem: {
    width: "48%",
    backgroundColor: COLOR.surface,
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  valueIcon: { fontSize: 32, marginBottom: 8, color: COLOR.text },
  valueTitle: { fontSize: 16, fontWeight: "900", color: COLOR.text, marginBottom: 4 },
  valueDescription: { fontSize: 12, color: COLOR.textDim, textAlign: "center", lineHeight: 16 },

  achievementsGrid: { flexDirection: "row", flexWrap: "wrap", gap: SPACE.md },
  achievementCard: {
    width: "48%",
    backgroundColor: "#fff7ed",
    padding: SPACE.lg,
    borderRadius: RADIUS.lg,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#fed7aa",
  },
  achievementNumber: { fontSize: 24, fontWeight: "900", color: "#b45309", marginBottom: 4 },
  achievementLabel: { fontSize: 14, color: "#b45309", textAlign: "center" },

  timelineContainer: { gap: SPACE.lg },
  timelineItem: { flexDirection: "row", gap: SPACE.md },
  timelineYear: {
    backgroundColor: COLOR.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    alignSelf: "flex-start",
  },
  timelineYearText: { fontSize: 12, color: "#ffffff", fontWeight: "900" },
  timelineContent: { flex: 1 },
  timelineTitle: { fontSize: 16, fontWeight: "900", color: COLOR.text, marginBottom: 4 },
  timelineDescription: { fontSize: 14, color: COLOR.textDim, lineHeight: 20 },

  teamIntroText: { fontSize: 14, color: COLOR.textDim, lineHeight: 20, textAlign: "center" },
  teamMembersContainer: { gap: SPACE.md },
  teamMemberCard: {
    backgroundColor: COLOR.surface,
    marginHorizontal: SPACE.lg,
    marginVertical: 5,
    borderRadius: RADIUS.lg,
    padding: SPACE.lg,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACE.md,
    borderWidth: 1,
    borderColor: COLOR.line,
    ...SHADOW,
  },
  teamMemberAvatar: { fontSize: 48, color: COLOR.text },
  teamMemberInfo: { flex: 1 },
  teamMemberName: { fontSize: 18, fontWeight: "900", color: COLOR.text, marginBottom: 4 },
  teamMemberPosition: { fontSize: 14, color: COLOR.primary, fontWeight: "800", marginBottom: 8 },
  teamMemberDescription: { fontSize: 12, color: COLOR.textDim, lineHeight: 16 },

  cultureContainer: { gap: SPACE.md },
  cultureItem: {
    backgroundColor: "#f9fafb",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  cultureIcon: { fontSize: 24, marginBottom: 8, color: COLOR.text },
  cultureTitle: { fontSize: 16, fontWeight: "900", color: COLOR.text, marginBottom: 6 },
  cultureText: { fontSize: 14, color: COLOR.textDim, lineHeight: 18 },

  contactInfoContainer: { gap: SPACE.md },
  contactInfoItem: { flexDirection: "row", alignItems: "center", gap: SPACE.md, paddingVertical: 10 },
  contactInfoIcon: { fontSize: 24, width: 30, textAlign: "center", color: COLOR.text },
  contactInfoContent: { flex: 1 },
  contactInfoTitle: { fontSize: 14, fontWeight: "900", color: COLOR.text, marginBottom: 2 },
  contactInfoText: { fontSize: 14, color: COLOR.textDim },

  socialMediaContainer: { flexDirection: "row", gap: SPACE.md },
  socialMediaButton: {
    flex: 1,
    backgroundColor: "#f9fafb",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.line,
  },
  socialMediaIcon: { fontSize: 24, marginBottom: 8, color: COLOR.text },
  socialMediaText: { fontSize: 14, fontWeight: "800", color: COLOR.text },

  workingHoursContainer: { gap: SPACE.sm },
  workingHoursItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: SPACE.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#f2f4f7",
  },
  workingHoursDay: { fontSize: 14, color: COLOR.text, fontWeight: "800" },
  workingHoursTime: { fontSize: 14, color: COLOR.textDim },

  supportNote: {
    backgroundColor: "#ecfdf5",
    padding: SPACE.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: "#bbf7d0",
  },
  supportNoteIcon: { fontSize: 24, marginBottom: 8, color: COLOR.success },
  supportNoteTitle: { fontSize: 16, fontWeight: "900", color: COLOR.success, marginBottom: 6 },
  supportNoteText: { fontSize: 14, color: "#14532d", lineHeight: 18 },
});
